times:
  24000: #day
    in: "&aMorning in &6%s"
    is: "&aIt's the morning!"
    title: "&aIt's the morning!"
    subtitle: "&aGood morning =)"
    soundIn: BLOCK_NOTE_BLOCK_BELL
    sound: BLOCK_NOTE_BLOCK_BELL
    commands:
      - "gamerule keepInventory true"
  13000: #night
    in: "&cNight in &6%s"
    is: "&cIt's night!"
    title: "&cIt's night!"
    subtitle: "&cIt's getting dark here..."
    soundIn: AMBIENT_CAVE
    sound: AMBIENT_CAVE
    commands:
      - "gamerule keepInventory false"

fadeIn: 5
stay: 20
fadeOut: 5